version: "3.3"

services:
  api:
    container_name: booking-api
    build:
      context: ./.docker
    volumes:
      - ./:/var/www/app
    links:
      - db
    depends_on:
      - db
    environment:
      - APP_NAME=Lumen
      - APP_ENV=local
      - APP_KEY=123456
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - LOG_SLACK_WEBHOOK_URL=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=ivao
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    ports:
      - 8080:80
  db:
    container_name: booking-db
    image: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=ivao
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./.docker/mysql:/var/lib/mysql
